openapi: 3.0.0
info:
  title: Resource Ordering Management
  description: This is Swagger UI environment generated for the TMF Resource Ordering
    Management specification
  version: 4.1.3
servers:
- url: https://virtserver.swaggerhub.com/Masmovil/Masinstallations/4.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: resourceOrder
paths:
  /resourceOrder:
    get:
      tags:
      - resourceOrder
      summary: List or find ResourceOrder objects
      description: This operation list or find ResourceOrder entities
      operationId: listResourceOrder
      parameters:
      - name: fields
        in: query
        description: Comma-separated properties to be provided in response
        required: false
        style: form
        explode: true
      - name: offset
        in: query
        description: Requested index for start of resources to be provided in response
        required: false
        style: form
        explode: true
      - name: limit
        in: query
        description: Requested number of resources to be provided in response
        required: false
        style: form
        explode: true
      responses:
        "200":
          description: Success
          headers:
            X-Result-Count:
              description: Actual number of items returned in the response body
              style: simple
              explode: false
            X-Total-Count:
              description: Total number of items matching criteria
              style: simple
              explode: false
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "405":
          description: Method Not allowed
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
    post:
      tags:
      - resourceOrder
      summary: Creates a ResourceOrder
      description: This operation creates a ResourceOrder entity.
      operationId: createResourceOrder
      parameters: []
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "405":
          description: Method Not allowed
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
  /resourceOrder/{id}:
    get:
      tags:
      - resourceOrder
      summary: Retrieves a ResourceOrder by ID
      description: This operation retrieves a ResourceOrder entity. Attribute selection
        is enabled for all first level attributes.
      operationId: retrieveResourceOrder
      parameters:
      - name: id
        in: path
        description: Identifier of the ResourceOrder
        required: true
        style: simple
        explode: false
      - name: fields
        in: query
        description: Comma-separated properties to provide in response
        required: false
        style: form
        explode: true
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "405":
          description: Method Not allowed
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
    put:
      tags:
      - resourceOrder
      summary: Updates totally a ResourceOrder
      description: This operation updates totally a ResourceOrder entity.
      operationId: putResourceOrder
      parameters:
      - name: id
        in: path
        description: Identifier of the ResourceOrder
        required: true
        style: simple
        explode: false
      responses:
        "200":
          description: Updated
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "405":
          description: Method Not allowed
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
    delete:
      tags:
      - resourceOrder
      summary: Deletes a ResourceOrder
      description: This operation deletes a ResourceOrder entity.
      operationId: deleteResourceOrder
      parameters:
      - name: id
        in: path
        description: Identifier of the ResourceOrder
        required: true
        style: simple
        explode: false
      responses:
        "204":
          description: Deleted
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "405":
          description: Method Not allowed
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
    patch:
      tags:
      - resourceOrder
      summary: Updates partially a ResourceOrder
      description: This operation updates partially a ResourceOrder entity.
      operationId: patchResourceOrder
      parameters:
      - name: id
        in: path
        description: Identifier of the ResourceOrder
        required: true
        style: simple
        explode: false
      responses:
        "200":
          description: Updated
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "405":
          description: Method Not allowed
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
components: {}
